name: pyts2
channels:
  - conda-forge
dependencies:
  - python=3.*
  - click
  - flask
  - imageio
  - iso8601
  - msgpack-python
  - numpy
  - opencv
  - scikit-image
  - tqdm
  - zbarlight
  - pip
  - pip:
    - rawpy
    - tqdm
    - datetime_truncate
